import streamlit as st
import pandas as pd
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Set page config
st.set_page_config(page_title="ChatAI Data Analyst", layout="wide")

# Import our agent and environment
from chatai_data_analyst import agent, python_repl_env

st.title("ChatAI - Data Analyst")
st.markdown("Upload a CSV file and ask questions about your data.")

# Sidebar for file upload
with st.sidebar:
    st.header("Upload Data")
    uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])
    
    if uploaded_file is not None:
        try:
            # Read CSV
            df = pd.read_csv(uploaded_file)
            
            # Replicate the original script's behavior of adding a revenue column if possible
            if "price" in df.columns and "quantity" in df.columns:
                 df["revenue"] = df["price"] * df["quantity"]
                 
            # Update the globals for the REPL environment
            python_repl_env.globals["df"] = df
            python_repl_env.globals["df2"] = df.copy()
            
            st.success(f"File '{uploaded_file.name}' loaded successfully!")
            st.write(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
            with st.expander("Show Data Preview"):
                st.dataframe(df.head())
                
        except Exception as e:
            st.error(f"Error loading file: {e}")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat messages from history on app rerun
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        if msg.get("text"):
            st.markdown(msg["text"])
        if msg.get("fig") is not None:
            st.plotly_chart(msg["fig"], use_container_width=True)

# Accept user input
if prompt := st.chat_input("Ask about your data (e.g., 'tell top 3 brands by revenue')"):
    # Require data upload first
    if uploaded_file is None:
        st.warning("Please upload a CSV file first from the sidebar.")
    else:
        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "text": prompt})
        
        # Display user message
        with st.chat_message("user"):
            st.markdown(prompt)

        # Display assistant response
        with st.chat_message("assistant"):
            # Clear previous figures to avoid repeating them
            python_repl_env.globals["last_fig"] = None
            
            with st.spinner("Analyzing..."):
                try:
                    # Inform agent with just the latest user text
                    response = agent.invoke({"messages": [("user", prompt)]})
                    
                    # Get final textual response
                    final_msg = response["messages"][-1]
                    result_text = final_msg.content
                    
                    # Display the text
                    if result_text:
                        st.markdown(result_text)
                        
                    # Check if a chart was generated by the plot_chart tool
                    fig = python_repl_env.globals.get("last_fig")
                    if fig is not None:
                        st.plotly_chart(fig, use_container_width=True)
                        
                    # Save to session state
                    st.session_state.messages.append({
                        "role": "assistant", 
                        "text": result_text, 
                        "fig": fig
                    })
                    
                except Exception as e:
                    st.error(f"Error analyzing data: {e}")
